import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import type { Locale } from '@rainbow-me/rainbowkit';
import Providers from "@/components/providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RainbowKit App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {children: React.ReactNode,
  params: Promise<{ locale: string }>
}) {
  const { children, params } = props;
  
  return (children);
    // <html
    //   lang="en" 
    //   className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    // >
    //   <body className="min-h-full flex flex-col">
    //     <Providers>
    //       <Header />
    //     </Providers>
    //     {children}
    //     <Footer />
    //   </body>
    // </html>
  
}
